
package compiladores.enums;

/**
 *
 * @author Siloe
 */
public enum TipoErro {
    
    ERRO_NAO_IDENTIFICADO, SIMBOLO_NAO_IDENTIFICADO, IDENTIFICADOR_MAL_FORMADO, SIMBOLO_MAL_FORMADO,
    OPERADOR_MAL_FORMADO, NUMERO_MAL_FORMADO,
    CADEIA_INCOMPLETA, CARACTERE_VAZIO, QUANTIDADE_DE_CARACTERES_INVALIDO;
    
}
