package compiladores.enums;

/**
 *
 * @author Siloe
 */
public enum TipoToken {

    IDENTIFICADOR, PALAVRA_RESERVADA, NUMERO_INTEIRO, NUMERO_REAL, CADEIA_CONSTANTE, CARACTERE_CONSTANTE,
    OPERADOR_RELACIONAL, OPERADOR_ARITMETICO_BINARIO, OPERADOR_ARITMETICO_UNARIO,
    OPERADOR_ARITMETICO_ATRIBUICAO, OPERADOR_ARITMETICO_LOGICO,
    OPERADOR_ARITMETICO_ACESSO, DELIMITADOR_FIM_LINHA, DELIMITADOR_SEPARADOR,
    DELIMITADOR_ABRIR_PARENTESE, DELIMITADOR_FECHAR_PARENTESE, DELIMITADOR_ABRIR_CHAVES, DELIMITADOR_FECHAR_CHAVES,
    DELIMITADOR_ABRIR_COLCHETE, DELIMITADOR_FECHAR_COLCHETE, COMENTARIO;
}
